export const RECEIVE_USERINFO = 'RECEIVE_USERINFO'
export const RECEIVE_ARTICLELIST = 'RECEIVE_ARTICLELIST'

export const RECEIVE_SUBJECTCONTENT = 'RECEIVE_SUBJECTCONTENT'
export const RECEIVE_SUBJECTSTATUS = 'RECEIVE_SUBJECTSTATUS'
export const RECEIVE_SUBJECTATTACHMENT = 'RECEIVE_SUBJECTATTACHMENT'